import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import puppeteer from "puppeteer"

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession()
    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await req.json()
    const { content, title, language } = body as {
      content: string
      title: string
      language: string
    }

    if (!content || !title) {
      return NextResponse.json(
        { error: "Content and title are required" },
        { status: 400 }
      )
    }

    const formattedContent = content
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "<br/>")

    const html = `
      <!DOCTYPE html>
      <html lang="${language === "hi" ? "hi" : "en"}">
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: Arial, sans-serif;
            background: #ffffff;
            color: #1a1a1a;
            font-size: 13px;
            line-height: 1.7;
          }
          .page {
            max-width: 794px;
            margin: 0 auto;
            padding: 60px 64px;
            min-height: 1123px;
            position: relative;
          }
          .watermark {
            position: fixed;
            top: 0;
            right: 0;
            width: 4px;
            height: 100%;
            background: #FF5C1A;
          }
          .header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding-bottom: 24px;
            border-bottom: 2px solid #FF5C1A;
            margin-bottom: 40px;
          }
          .logo-text {
            font-size: 20px;
            font-weight: 700;
            color: #1a1a1a;
          }
          .logo-text span { color: #FF5C1A; }
          .doc-type {
            font-size: 11px;
            font-weight: 600;
            color: #FF5C1A;
            text-transform: uppercase;
            letter-spacing: 1.5px;
            text-align: right;
          }
          .doc-date {
            font-size: 11px;
            color: #888;
            margin-top: 3px;
            text-align: right;
          }
          .doc-title {
            font-size: 20px;
            font-weight: 700;
            color: #1a1a1a;
            margin-bottom: 8px;
          }
          .doc-subtitle {
            font-size: 11px;
            color: #888;
            margin-bottom: 32px;
            padding-bottom: 20px;
            border-bottom: 1px solid #f0f0f0;
          }
          .content h1 {
            font-size: 16px;
            font-weight: 700;
            margin: 24px 0 10px;
          }
          .content h2 {
            font-size: 13px;
            font-weight: 600;
            color: #FF5C1A;
            margin: 20px 0 8px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .content p { margin-bottom: 12px; }
          .content li {
            margin-bottom: 8px;
            margin-left: 20px;
          }
          .content strong { font-weight: 600; }
          .footer {
            position: absolute;
            bottom: 40px;
            left: 64px;
            right: 64px;
            display: flex;
            justify-content: space-between;
            padding-top: 16px;
            border-top: 1px solid #f0f0f0;
            font-size: 10px;
            color: #aaa;
          }
          .footer-brand { color: #FF5C1A; font-weight: 600; }
        </style>
      </head>
      <body>
        <div class="page">
          <div class="watermark"></div>
          <div class="header">
            <div class="logo-text">Bharat<span>Comply</span></div>
            <div>
              <div class="doc-type">Legal Document</div>
              <div class="doc-date">Generated on ${new Date().toLocaleDateString("en-IN", {
                day: "numeric",
                month: "long",
                year: "numeric",
              })}</div>
            </div>
          </div>
          <div class="doc-title">${title}</div>
          <div class="doc-subtitle">
            Generated by BharatComply AI · ${language === "hi" ? "हिंदी में" : "In English"} · Confidential
          </div>
          <div class="content">
            <p>${formattedContent}</p>
          </div>
          <div class="footer">
            <div>This document was AI-generated. Please verify before legal use.</div>
            <div>Powered by <span class="footer-brand">BharatComply</span></div>
          </div>
        </div>
      </body>
      </html>
    `

    const browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
      ],
    })

    const page = await browser.newPage()

    await page.setContent(html, {
      waitUntil: "load",
    })

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "0px",
        right: "0px",
        bottom: "0px",
        left: "0px",
      },
    })

    await browser.close()

    return new NextResponse(Buffer.from(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${title.replace(/[^a-z0-9]/gi, "_")}.pdf"`,
      },
    })
  } catch (error) {
    console.error("PDF generation error:", error)
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    )
  }
}